<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuiteForDataDrivenTests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ba8a78cc-56f4-4a6e-9bf8-5df738f49db5</testSuiteGuid>
   <testCaseLink>
      <guid>a81ff320-0ce5-40f9-9643-fdc3c23248a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NOPCOMMERCE/MYACCOUNT/Proces rejestracji</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ebf7454a-b6d8-42bc-9665-ba08ddcdd86a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ebf7454a-b6d8-42bc-9665-ba08ddcdd86a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>c68502f6-b330-4941-9557-c89774cb4d0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ebf7454a-b6d8-42bc-9665-ba08ddcdd86a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>f400bef7-79b5-4341-974d-690b3bd3d6fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35f1a617-7d02-4ab4-bac8-b50b22f00c11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0ce0cca-5720-4786-ad99-dd329ef698ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3519b8e-3180-4161-918a-aff00d7e59dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ebf7454a-b6d8-42bc-9665-ba08ddcdd86a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>d4b86fbe-7f99-43e4-ae2a-ff6d0ee6ebe5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ebf7454a-b6d8-42bc-9665-ba08ddcdd86a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CompanyName</value>
         <variableId>29eb0b6d-f4c9-4333-a67d-4bd227addd03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ebf7454a-b6d8-42bc-9665-ba08ddcdd86a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>050d7995-fd47-45cc-8626-5afde1df7f46</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
